svgframes = infinity_frames

frames: Libertarians

Libertarians:
	inkscape --export-filename="Libertarians.png" --export-id="Libertarians-bg" \
	--export-type="png" $(svgframes).svg

clean:
	rm Libertarians.png
