frames: blank title c1928 rhode-island ice-dam ef1632 tower-concept

blank:
	inkscape --export-filename="blank.png" --export-id="blank-violet" \
	--export-type="png" challenge_frames.svg
title:
	inkscape --export-filename="title_card.png" --export-id="title-card" \
	--export-type="png" challenge_frames.svg
c1928:
	inkscape --export-filename="B 1928.png" --export-id="year-c-1928" \
	--export-type="png" challenge_frames.svg
rhode-island:
	inkscape --export-filename="B RI.png" --export-id="rhode-island" \
	--export-type="png" challenge_frames.svg
ice-dam:
	inkscape --export-filename="B ice-dam.png" --export-id="ice-dam" \
	--export-type="png" challenge_frames.svg
ef1632:
	inkscape --export-filename="B 1632.png" --export-id="bg-1632" \
	--export-type="png" challenge_frames.svg
tower-concept:
	inkscape --export-filename="B concept.png" --export-id="tower-concept" \
	--export-type="png" challenge_frames.svg

# timeline: just copy png from fan2 when that is added. it's more trouble to include all the svg here

clean:
	rm blank.png title_card.png \
	"B 1928.png" "B RI.png" "B ice-dam.png" "B 1632.png" \
	"B concept.png"
